# PLACEHOLDER hardware configuration for vm-guest.
#
# This is a generic UEFI + virtio layout that lets the flake evaluate and lets
# `nixos-install --flake .#vm-guest` proceed. During the install (see
# docs/vm-guest-install.md) you REPLACE this file with the real one generated by
# `nixos-generate-config --root /mnt` inside the VM, which fills in the actual
# partition UUIDs. The device paths below assume the standard install layout:
#   /dev/vda1  ESP  (vfat) -> /boot
#   /dev/vda2  root (ext4) -> /
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/ESP";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
